export const ICONS = {
    ic_landing: require('../assets/logoLanding.png'),
    ic_familyLogin: require('../assets/familyLogin.png'),
    ic_eyeClose: require('../assets/EyeClose.png'),
    ic_eyeOpen: require('../assets/EyeOpen.png'),
    ic_gg: require('../assets/icgg.png'),
    ic_fb: require('../assets/icfb.png'),
    ic_avatar_create_home: require('../assets/ic_avatar_create_home.png'),
    ic_Qr_code: require('../assets/QRcode.png'),
    ic_home: require('../assets/bxs-home.png'),
    ic_time_line: require('../assets/bxs-detail.png'),
    ic_message: require('../assets/bxs-chat.png'),
    ic_account: require('../assets/bxs-user-circle.png'),
    ic_red_call: require('../assets/ButtonCall.png'),
    ic_home_selectDepartment: require('../assets/homeSelectDepartment.png'),
    ic_chevron_down: require('../assets/chevronDown.png'),
    ic_avatar: require('../assets/Avatar.png'),
    ic_visitors: require('../assets/icServices.home/Visitors.png'),
    ic_parcels: require('../assets/icServices.home/Parcels.png'),
    ic_services: require('../assets/icServices.home/Services.png'),
    ic_bills: require('../assets/icServices.home/Bills.png'),
    ic_notiHome: require('../assets/icNoti.png'),


}